---
goldenjson: analysis/data/Cert_Collisions2022_355100_362760_Golden.txt
lumidata: analysis/data/lumi2022.csv
hlt_paths:
  - IsoMu24
object_selection:
  leptons:
    field: events.Muon
    cuts:
      pt: events.Muon.pt > 24
      abseta: np.abs(events.Muon.eta) < 2.4
      dxy: events.Muon.dxy < 0.5
      dz: events.Muon.dz < 1
      sip3d: events.Muon.sip3d < 4
      muon_id: tight
      muon_iso: tight
  dileptons:
    field: select_dileptons
    cuts:
      dr: ((LorentzVector.delta_r(objects['dileptons'].z.leading_lepton,
        objects['dileptons'].z.subleading_lepton) > 0.02))
      mass_window: (objects['dileptons'].z.p4.mass < 120.0) &
        (objects['dileptons'].z.p4.mass > 60.0)
event_selection:
  atleast_one_goodvertex: events.PV.npvsGood > 0
  lumimask: get_lumi_mask(events, goldenjson)
  trigger: get_trigger_mask(events, hlt_paths)
  trigger_matching: get_trigger_match_mask(events, events.Muon, hlt_paths)
  two_leptons: ak.num(objects['leptons']) == 2
  one_z: ak.num(objects['dileptons'].z.p4) == 1
histogram_config:
  add_syst_axis: true
  add_weight: true
  add_cat_axis: null
  axes:
    dimuon_mass:
      type: Regular
      bins: 100
      start: 10
      stop: 150
      label: r"$m(\mu\mu)$ [GeV]"
      expression: objects['dileptons'].z.p4.mass
    dimuon_pt:
      type: Regular
      bins: 50
      start: 30
      stop: 300
      label: r"$p_T(\mu\mu)$ [GeV]",
      expression: objects['dileptons'].z.p4.pt
    leading_muon_pt:
      type: Regular
      bins: 50
      start: 30
      stop: 300
      label: r"$p_T(\mu_1)$ [GeV]"
      expression: objects['dileptons'].z.leading_lepton.pt
    subleading_muon_pt:
      type: Regular
      bins: 50
      start: 30
      stop: 300
      label: r"$p_T(\mu_2)$ [GeV]"
      expression: objects['dileptons'].z.subleading_lepton.pt
    muon_pt:
      type: Regular
      bins: 50
      start: 30
      stop: 300
      label: r"$p_T(\mu)$ [GeV]"
      expression: objects['leptons'].pt
    muon_eta:
      type: Regular
      bins: 50
      start: -2.5
      stop: 2.5
      label: r"$\eta(\mu)$"
      expression: objects['leptons'].eta
    muon_phi:
      type: Regular
      bins: 50
      start: -3.14159
      stop: 3.14159
      label: r"$\phi(\mu)$"
      expression: objects['leptons'].phi
  layout:
    zcandidate:
      - dimuon_mass
      - dimuon_pt
      - leading_muon_pt
      - subleading_muon_pt
    muon:
      - muon_pt
      - muon_eta
      - muon_phi